config/routes.rb
Rails.application.routes.draw do
  root 'papers#index'

#---custom routes of papers controller------
  get '/papers', to: 'papers#index'

  post '/papers', to: 'papers#create'

  get '/papers/new', to: 'papers#new', as: 'new_paper'

  get '/papers/:id', to: 'papers#show', as: 'paper'

  get '/papers/:id/edit', to: 'papers#edit', as: 'edit_paper'

  patch '/papers/:id', to: 'papers#update'

  put '/papers/:id', to: 'papers#update'

  delete '/papers/:id', to: 'papers#destroy'

  resources :trips

#-------namespace and scope ------------
  # namespace :admin do
  #   resources :articles, :comments
  # end

  # scope  path: 'custom' do
  #   resources :articles
  # end


#----- shallow option ---------------
  # resources :articles do
  #   resources :comments, shallow: true
  # end

#   scope shallow_path: "sekret" do
#     resources :articles do
#       resources :comments, shallow: true
#     end
#   end


# #---- member and collection routes ---
#   resources :photos do
#     member do
#       get :preview
#     end
#   end

#   resources :photos do
#     collection do
#       get :search
#     end
#   end


#---- redirection -----------
#   get '/papers', to: redirect('/articles')


#----- resolve -------------
  
  #resource :article

   #resolve("Article") { [:article] }


#---  routes name helper overriding -----
resources :photos, controller: 'images'


#-----Override new and edit --------
resources :abc, path_names: { new: 'latest', edit: 'change' }

  # scope module: 'admin', path: 'hello', as: 'cool' do
  #   get '/phones/new', to: 'phones#new', as: 'new_phone'
  # end

  # get 'articles/*section/:title', to: 'articles#show'

  resources :users do
    get 'search', on: :collection
  end

  # resources :post, shallow: true do
  #   resources :commentss
  #   resources :quotes
  #   resources :drafts
  # end 

  resources :basket

resolve("Basket") { [:basket] } 

  resources :articles do
    resources :comments
  end

end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :supplier
  belongs_to :editor
  has_many :reviews
  has_and_belongs_to_many :orders, join_table: 'papers_orders'

  #scope :out_of_print, -> { where(out_of_print: true) }
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  def index
    @papers = Paper.all
  end

  def show
    @paper = Paper.find(params[:id])
  end

  def new
    @paper = Paper.new
  end

  def create
    # debugger
    @paper = Paper.new(paper_params)

    if @paper.save
      flash[:notice] = "You have registered succesfully."

      redirect_to @paper
    else
      render "new"
    end
  end

  def edit
    @paper = Paper.find(params[:id])
  end

  def update
    @paper = Paper.find(params[:id])

    if @paper.update(paper_params)
      redirect_to @paper
    else
      render "edit"
    end
  end

  private
    def paper_params
      params.require(:paper).permit(:title, :price, :out_of_print, :supplier_id, :editor_id, :picture)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with model: @paper do |form| %>
  <h5> Title:- <%= form.text_field :title %> </h5>

  <%= form.number_field :price %>
  <%= form.check_box :out_of_print %>
  <%= form.collection_select :supplier_id, Supplier.order(:name), :id, :name %>
  <%= form.collection_select :editor_id, Editor.order(:name), :id, :name %>
  <%= form.submit %>
<% end %>

app/views/papers/edit.html.erb
<h3>Edit this :--</h3>

<%= render "form"%>

app/views/papers/index.html.erb
<h3> Fill this form</h3>


<%= link_to "New Article", new_paper_path %>

<!-- <h3>@paper.title </h3> -->

<h4>List of all papers</h4>
<ul>
  <% @papers.each do |paper| %>
    <li>
      <%= link_to paper.title, paper %>
    </li>
  <% end %>
</ul>

app/views/papers/new.html.erb
 <h3> Fill this form</h3>

<%= render "form"%>


<%= link_to "Go to index page", papers_path %>

app/views/papers/new_file.html.erb
this is second file for demo

app/views/papers/new_file_for_demo.html.erb
this is new file

this is changed by another bracnh called new_branch..

hello friends :-

changed.........

app/views/papers/show.html.erb
<h3>Welcome :- </h3>

<h3> Title :- <%= @paper.title %> </h3>

<h3> Price :- <%= @paper.price %> </h3>

<h3> Out of print :- <%= @paper.out_of_print %> </h1>

<h4> Supplier :- <%= @paper.supplier.name %> </h1>
<h4> Editor of this news paper :- <%= @paper.editor.name %> </h1>

	<h4> Edit this <%= link_to "Edit", edit_paper_path(@paper) %></h4>   
<h4> <%= button_to 'Delete',  paper_path(@paper),  method: :delete %> </h4>

<%= link_to "Go to home page", root_path %>